-- Add some Richmond, VA businesses
INSERT INTO businesses (
  id, name, email, phone, address, city, state, zipcode,
  category, subcategory, description, services, is_verified, 
  is_featured, rating, reviews, response_time_hours, 
  license_number, insurance_verified, same_day_available, created_at
) VALUES 
(
  gen_random_uuid(),
  'Richmond Dumpster Pros',
  'info@richmonddumpsterpros.com',
  '(804) 555-0100',
  '123 Main St',
  'Richmond',
  'VA',
  '23219',
  'waste_management',
  'dumpster_rental',
  'Premier dumpster rental service in Richmond area',
  '["10-yard dumpster", "20-yard dumpster", "30-yard dumpster", "40-yard dumpster"]',
  true,
  true,
  4.8,
  145,
  2,
  'VA-WM-2024001',
  true,
  true,
  NOW()
),
(
  gen_random_uuid(),
  'Capital City Waste Solutions',
  'contact@capitalcitywaste.com',
  '(804) 555-0200',
  '456 Broad St',
  'Richmond',
  'VA',
  '23220',
  'waste_management',
  'dumpster_rental',
  'Reliable waste management for Richmond businesses and residents',
  '["15-yard dumpster", "20-yard dumpster", "30-yard dumpster"]',
  true,
  false,
  4.6,
  89,
  4,
  'VA-WM-2024002',
  true,
  false,
  NOW()
),
(
  gen_random_uuid(),
  'RVA Roll-Off Rentals',
  'service@rvarolloff.com',
  '(804) 555-0300',
  '789 Grace St',
  'Richmond',
  'VA',
  '23221',
  'waste_management',
  'dumpster_rental',
  'Fast and affordable dumpster rentals in RVA',
  '["10-yard dumpster", "20-yard dumpster", "40-yard dumpster"]',
  true,
  true,
  4.9,
  203,
  1,
  'VA-WM-2024003',
  true,
  true,
  NOW()
);