-- Insert sample businesses
INSERT INTO businesses (
  name, category, description, rating, reviews, phone, email, website,
  address, city, state, zipcode, latitude, longitude,
  is_featured, is_verified, is_claimed, featured_until,
  logo_url, cover_image, years_in_business, license_number, insurance,
  price_range, services, service_areas, hours, certifications,
  owner_name, owner_email
) VALUES
(
  'R&L Dumpsters',
  'Dumpster Rental',
  'Professional dumpster rental service for residential and commercial projects. Family-owned and operated since 2015.',
  5.0,
  31,
  '(936) 236-9474',
  'info@rldumpsters.com',
  'https://rldumpsters.com',
  '1714 W Little York Rd',
  'Houston',
  'TX',
  '77091',
  29.805742,
  -96.1381324,
  true,
  true,
  true,
  NOW() + INTERVAL '1 year',
  'https://ext.same-assets.com/1079325698/1963887577.webp',
  'https://ext.same-assets.com/1079325698/1819760783.webp',
  8,
  'TX-DMP-2015-1234',
  true,
  'moderate',
  '[
    {"id": "1", "name": "10 Yard Dumpster", "description": "Perfect for small cleanouts", "price_from": 275, "price_to": 350, "price_unit": "rental"},
    {"id": "2", "name": "20 Yard Dumpster", "description": "Ideal for medium projects", "price_from": 375, "price_to": 450, "price_unit": "rental"},
    {"id": "3", "name": "30 Yard Dumpster", "description": "Great for large renovations", "price_from": 475, "price_to": 550, "price_unit": "rental"}
  ]'::jsonb,
  '["Houston", "Spring", "The Woodlands", "Conroe", "Katy"]'::jsonb,
  '{
    "monday": {"open": "7:00 AM", "close": "6:00 PM"},
    "tuesday": {"open": "7:00 AM", "close": "6:00 PM"},
    "wednesday": {"open": "7:00 AM", "close": "6:00 PM"},
    "thursday": {"open": "7:00 AM", "close": "6:00 PM"},
    "friday": {"open": "7:00 AM", "close": "6:00 PM"},
    "saturday": {"open": "8:00 AM", "close": "4:00 PM"},
    "sunday": {"closed": true}
  }'::jsonb,
  '["EPA Certified", "OSHA Compliant"]'::jsonb,
  'Ricardo Romero',
  'ricardo@rldumpsters.com'
),
(
  'Quick Disposal Services',
  'Dumpster Rental',
  'Fast and reliable waste management solutions for all your project needs.',
  4.8,
  127,
  '(832) 555-0102',
  'contact@quickdisposal.com',
  'https://quickdisposal.com',
  '5678 Main St',
  'Houston',
  'TX',
  '77002',
  29.7604,
  -95.3698,
  true,
  true,
  false,
  NOW() + INTERVAL '6 months',
  'https://ext.same-assets.com/1079325698/1963887577.webp',
  'https://ext.same-assets.com/1079325698/3377177075.webp',
  12,
  'TX-WM-2011-5678',
  true,
  'premium',
  '[
    {"id": "1", "name": "15 Yard Dumpster", "price_from": 325, "price_to": 400, "price_unit": "rental"},
    {"id": "2", "name": "40 Yard Dumpster", "price_from": 575, "price_to": 650, "price_unit": "rental"}
  ]'::jsonb,
  '["Houston", "Pearland", "Sugar Land"]'::jsonb,
  '{
    "monday": {"open": "6:00 AM", "close": "8:00 PM"},
    "tuesday": {"open": "6:00 AM", "close": "8:00 PM"},
    "wednesday": {"open": "6:00 AM", "close": "8:00 PM"},
    "thursday": {"open": "6:00 AM", "close": "8:00 PM"},
    "friday": {"open": "6:00 AM", "close": "8:00 PM"},
    "saturday": {"open": "7:00 AM", "close": "6:00 PM"},
    "sunday": {"open": "8:00 AM", "close": "4:00 PM"}
  }'::jsonb,
  '["ISO 9001", "BBB Accredited"]'::jsonb,
  NULL,
  NULL
),
(
  'EcoWaste Solutions',
  'Dumpster Rental',
  'Environmentally conscious waste disposal with recycling options.',
  4.6,
  89,
  '(713) 555-0103',
  'info@ecowaste.com',
  'https://ecowaste.com',
  '9012 Oak Ave',
  'Houston',
  'TX',
  '77008',
  NULL,
  NULL,
  false,
  true,
  true,
  NULL,
  'https://ext.same-assets.com/1079325698/1963887577.webp',
  'https://ext.same-assets.com/1079325698/4115846507.webp',
  5,
  NULL,
  true,
  'moderate',
  NULL,
  '["Houston", "Bellaire", "West University"]'::jsonb,
  NULL,
  '["Green Business Certified"]'::jsonb,
  'Sarah Johnson',
  'sarah@ecowaste.com'
),
(
  'Budget Bins Rental',
  'Dumpster Rental',
  'Affordable dumpster rental solutions without compromising quality.',
  4.4,
  56,
  '(281) 555-0104',
  NULL,
  NULL,
  '3456 Elm St',
  'Spring',
  'TX',
  '77379',
  NULL,
  NULL,
  false,
  false,
  false,
  NULL,
  'https://ext.same-assets.com/1079325698/1963887577.webp',
  NULL,
  3,
  NULL,
  true,
  'budget',
  NULL,
  '["Spring", "The Woodlands", "Tomball"]'::jsonb,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'Premier Waste Management',
  'Dumpster Rental',
  'Premium service for construction sites and large commercial projects.',
  4.9,
  203,
  '(832) 555-0105',
  'sales@premierwaste.com',
  'https://premierwaste.com',
  '7890 Industrial Blvd',
  'Houston',
  'TX',
  '77015',
  NULL,
  NULL,
  true,
  true,
  true,
  NOW() + INTERVAL '1 year',
  'https://ext.same-assets.com/1079325698/1963887577.webp',
  'https://ext.same-assets.com/1079325698/3414646618.webp',
  15,
  'TX-WM-2009-5678',
  true,
  'luxury',
  '[
    {"id": "1", "name": "Commercial Dumpsters", "description": "Permanent solutions for businesses", "price_from": 150, "price_to": 500, "price_unit": "month"},
    {"id": "2", "name": "Construction Roll-offs", "description": "Heavy-duty containers", "price_from": 500, "price_to": 800, "price_unit": "rental"}
  ]'::jsonb,
  '["Greater Houston Area"]'::jsonb,
  '{
    "monday": {"open": "24 hours"},
    "tuesday": {"open": "24 hours"},
    "wednesday": {"open": "24 hours"},
    "thursday": {"open": "24 hours"},
    "friday": {"open": "24 hours"},
    "saturday": {"open": "24 hours"},
    "sunday": {"open": "24 hours"}
  }'::jsonb,
  '["ISO 9001", "SWANA Certified", "LEED Certified"]'::jsonb,
  'Michael Chen',
  'mchen@premierwaste.com'
);
